# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ii9u0fC3aPMiDcYae29Q-Ii-_aLJ1pZj
"""

pip install matplotlib

pip install numpy

# Estas ordenes son para importar las librerias
# intervalos aleatorios en numeros enteros entre a y b con radint desde random
import numpy as np
import matplotlib.pyplot as plt
from random import randint
# 12 niveles
levels = 12
#inciamos el programa y le damos 3 segundos de tiempo para que inicie solo
print("Bienvenido a la maquina de Galton")
print("El programa inciara en 3 segundos")
import time
time.sleep(3)
#Estas son las ordenes para asegurar el factor random
lanes = [0]*(levels)
for h in range(3000):
  stored = -1
  for j in range(levels):
    stored += randint(0, 1)
  lanes[stored] += 1
#Imprimimos el numero de canicas usadas
print(3000, "Canicas usadas en total")
#imprimimos en pantalla la grafica de galton
print(lanes)
X = np.arange(-((len(lanes)/2)-.5), (len(lanes)/2)+.5)
plt.suptitle('Maquina de Galton')
plt.bar(X + 0.00, lanes, width=0.25)
plt.show()
plt.savefig("Grafica de Galton.png")